#!/usr/bin/env bash
# created by D. Zuliani (April 2004)

# base settings
PATH="$PATH:/opt/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:/opt/www/htdig/bin:/opt/kde/bin:/usr/lib/qt-3.0.4/bin:/usr/share/texmf/bin:/home/frednet/bin:."
JOB="$(basename "$0")"

# Script usage
if [[ -z "${1:-}" || $# -gt 1 ]]; then
   USAGE="\nUSAGE:\n$(basename "$0") [PID number]\nuse $JOB for killing JOB with [PID number] and its children"
   echo -e "$USAGE"
   exit 1
fi

# Capture PID number from line input
PIDFATHER="$1"

# Check if the process exits
if [[ "$(ps -ef | gawk -v pid_main="$PIDFATHER" '{if ($2==pid_main) print $0}' | wc -l)" != "0" ]]; then
    :
else
    echo "Process: ${PIDFATHER} not active"
    exit 1
fi

# iteratively find out the process and its children
mapfile -t PIDSCHILDREN < <(ps -ef | gawk -v pid_father="$PIDFATHER" '{if ($3==pid_father) print $2}')
if (( ${#PIDSCHILDREN[@]} != 0 )); then
   for PIDTODEL in "${PIDSCHILDREN[@]}"; do
        kill_family "$PIDTODEL"
   done
else
    :
fi

#  KILLING
PROC_NAME="$(ps -a | gawk -v pid_father="$PIDFATHER" '{if ($1==pid_father) print $4}')"
echo "killing: ${PIDFATHER} --> ${PROC_NAME}"
if [[ "$(ps -ef | gawk -v pid_main="$PIDFATHER" '{if ($2==pid_main) print $0}' | wc -l)" != "0" ]]; then
   kill -9 "$PIDFATHER"
   if [[ $? -eq 0 ]]; then
      echo "Process: ${PIDFATHER} --> ${PROC_NAME} killed"
   else
      echo "Process: ${PIDFATHER} --> ${PROC_NAME} kill Fail"
   fi
else 
   echo "Process: ${PIDFATHER} previously killed"
fi
