#!/bin/tcsh
set UTMZONE = 33
#echo 4323114.840 1018204.344 4562403.236 | cs2cs -r -f "%.3f"\
echo $2 $1 $3 | /usr/bin/cs2cs -f "%.3f"\
+proj=latlon +ellps=WGS84 +datum=WGS84\
+to +proj=utm +ellps=WGS84 +datum=WGS84 +zone=${UTMZONE} +units=m | awk '{printf("%10.3f\t%12.3f\t%12.3f\n",$1,$2,$3)}'
